// Mocks generated by Mockito 5.4.6 from annotations
// in book_search_bloc/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:book_search_bloc/data/datasources/book_api_service.dart' as _i2;
import 'package:book_search_bloc/data/datasources/book_local_service.dart'
    as _i3;
import 'package:book_search_bloc/data/models/book_model.dart' as _i7;
import 'package:book_search_bloc/data/repositories/book_repository_impl.dart'
    as _i4;
import 'package:book_search_bloc/domain/entities/book.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBookApiService_0 extends _i1.SmartFake
    implements _i2.BookApiService {
  _FakeBookApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookLocalService_1 extends _i1.SmartFake
    implements _i3.BookLocalService {
  _FakeBookLocalService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BookRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepositoryImpl extends _i1.Mock
    implements _i4.BookRepositoryImpl {
  MockBookRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BookApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeBookApiService_0(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i2.BookApiService);

  @override
  _i3.BookLocalService get localService =>
      (super.noSuchMethod(
            Invocation.getter(#localService),
            returnValue: _FakeBookLocalService_1(
              this,
              Invocation.getter(#localService),
            ),
          )
          as _i3.BookLocalService);

  @override
  _i5.Future<List<_i6.Book>> searchBooks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchBooks, [query]),
            returnValue: _i5.Future<List<_i6.Book>>.value(<_i6.Book>[]),
          )
          as _i5.Future<List<_i6.Book>>);

  @override
  _i5.Future<void> saveBook(_i7.BookModel? book) =>
      (super.noSuchMethod(
            Invocation.method(#saveBook, [book]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
